### ISSUE TITLE
Graph offset by a bit in the X direction

### ISSUE THREAD

**Issue by kayvonf** [jhong93/esper-tv-widget#1]
See attached screenshot of how the graph is offset:

<img width="1163" alt="Screen Shot 2019-05-15 at 3 41 28 PM" src="https://user-images.githubusercontent.com/741835/57814251-f9ce7d80-7727-11e9-8b7b-4059181029e3.png">

http://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222012-03-02%22%2C%22end_date%22%3A%222018-03-30%22%2C%22count%22%3A%22videotime%22%2C%22aggregate%22%3A%22year%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22WHERE%20channel%3D%5C%22CNN%5C%22%20AND%20iscommercial%3Dtrue%20NORMALIZE%20WHERE%20channel%3D%5C%22CNN%5C%22%22%7D%2C%7B%22color%22%3A%22%23F28E2B%22%2C%22text%22%3A%22WHERE%20channel%3D%5C%22FOX%5C%22%20AND%20iscommercial%3Dtrue%20NORMALIZE%20WHERE%20channel%3D%5C%22FOX%5C%22%22%7D%2C%7B%22color%22%3A%22%23E15759%22%2C%22text%22%3A%22WHERE%20channel%3D%5C%22MSNBC%5C%22%20AND%20iscommercial%3Dtrue%20NORMALIZE%20WHERE%20channel%3D%5C%22MSNBC%5C%22%22%7D%5D%7D

**Comment by jhong93** [comment]
This should be fixed now.
