### ISSUE TITLE
need to support onscreen.face=Trump AND onscreen.face=woman

### ISSUE THREAD

**Issue by kayvonf** [jhong93/esper-tv-widget#15]
This is not implemented, but it is a valid query that should be supported.

http://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222010-01-01%22%2C%22end_date%22%3A%222018-04-01%22%2C%22count%22%3A%22videotime%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22%20WHERE%20channel%3Dcnn%22%7D%2C%7B%22color%22%3A%22%23F28E2B%22%2C%22text%22%3A%22%20WHERE%20channel%3Dfox%22%7D%2C%7B%22color%22%3A%22%23E15759%22%2C%22text%22%3A%22%20WHERE%20channel%3Dmsnbc%22%7D%5D%7D

**Comment by jhong93** [comment]
Added functionality.
