### ISSUE TITLE
Searcching for caption text that doesn't exist yields server error

### ISSUE THREAD

**Issue by magrawala** [jhong93/esper-tv-widget#16]
http://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222010-01-01%22%2C%22end_date%22%3A%222018-04-01%22%2C%22count%22%3A%22videotime%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22%20WHERE%20caption.text%3D%5C%22buttigieg%5C%22%22%7D%5D%7D

**Comment by jhong93** [comment]
This error should be fixed now.
