### ISSUE TITLE
Clarify default normalize behavior regarding commercials

### ISSUE THREAD

**Issue by jhong93** [jhong93/esper-tv-widget#23]
The normalize query excludes commercial.

http://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222010-08-01%22%2C%22end_date%22%3A%222018-04-01%22%2C%22count%22%3A%22screen%20time%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20iscommercial%3Dboth%20NORMALIZE%20(all)%22%7D%2C%7B%22color%22%3A%22%23F28E2B%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20iscommercial%3Dtrue%20NORMALIZE%20(all)%22%7D%2C%7B%22color%22%3A%22%23E15759%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20iscommercial%3Dfalse%20NORMALIZE%20(all)%22%7D%5D%7D

**Comment by magrawala** [comment]
URL Doesn’t work for me.

Maneesh
