### ISSUE TITLE
Need to figure out how to do graph legends for embedded graphs.

### ISSUE THREAD

**Issue by kayvonf** [jhong93/esper-tv-widget#27]

**Comment by jhong93** [comment]
I am not sure what the enhancement is targeting here. We already have legends on embedded graphs.

https://esper-tv.stanford.edu/embed?width=1000&height=400&data=%7B%22options%22%3A%7B%22start_date%22%3A%222010-01-01%22%2C%22end_date%22%3A%222018-04-01%22%2C%22count%22%3A%22screen%20time%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20onscreen.face1%3D%5C%22person%3A%20hillary%20clinton%5C%22%22%7D%2C%7B%22color%22%3A%22%23F28E2B%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20onscreen.face1%3D%5C%22person%3A%20donald%20trump%5C%22%22%7D%5D%7D
