### ISSUE TITLE
"failed to load videos" error when clicking on a graph datapoint

### ISSUE THREAD

**Issue by kayvonf** [jhong93/esper-tv-widget#31]
Only when I run this query:
onscreen.face1="gender: male" and onscreen.facecount="2"

https://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222014-01-01%22%2C%22end_date%22%3A%222018-04-01%22%2C%22count%22%3A%22screen%20time%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20onscreen.face1%3D%5C%22gender%3A%20male%5C%22%20and%20onscreen.facecount%3D%5C%222%5C%22%22%7D%5D%7D

**Comment by kayvonf** [comment]
Update.  It seems to apply to any query where onscreen.facecount="" is used in the query.

Here's the simplest trigger:
onscreen.facecount=4

**Comment by jhong93** [comment]
Fixed now.
