### ISSUE TITLE
unknown server error when aggregated by day

### ISSUE THREAD

**Issue by kayvonf** [jhong93/esper-tv-widget#35]
Hillary vs. Trump query.

https://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222016-01-01%22%2C%22end_date%22%3A%222017-01-01%22%2C%22count%22%3A%22screen%20time%22%2C%22aggregate%22%3A%22week%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20onscreen.face1%3D%5C%22person%3A%20donald%20trump%5C%22%22%7D%2C%7B%22color%22%3A%22%23F28E2B%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20onscreen.face1%3D%5C%22person%3A%20hillary%20clinton%5C%22%22%7D%5D%7D

**Comment by jhong93** [comment]
I suspect this was when I restarted the server since I saw recent requests right before I did it.
