### ISSUE TITLE
non-uniform spacing of graph vertical ticks

### ISSUE THREAD

**Issue by kayvonf** [jhong93/esper-tv-widget#36]
https://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222016-07-01%22%2C%22end_date%22%3A%222016-08-15%22%2C%22count%22%3A%22screen%20time%22%2C%22aggregate%22%3A%22day%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20transcript.text%3D%5C%22democratic%20convention%5C%22%22%7D%2C%7B%22color%22%3A%22%23F28E2B%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20transcript.text%3D%5C%22republican%20convention%7Cgop%20convention%5C%22%22%7D%2C%7B%22color%22%3A%22%23E15759%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20transcript.text%3D%5C%22gop%20convention%5C%22%22%7D%5D%7D

**Comment by jhong93** [comment]
This is because vega-lite prefers to have an X axis tick on the 1st day of each month

**Comment by jhong93** [comment]
Closing due to query language changes (invalidating the link).
