### ISSUE TITLE
back-to-back cuts trick "A AND B" queries

### ISSUE THREAD

**Issue by kayvonf** [jhong93/esper-tv-widget#4]
query is screen time WHERE onscreen.face1=Donald Trump AND onscreen.face2=Hillary Clinton.

Note that some of the results thumbnails do not have both Hillary and Trump in them. It's because Hillary is there a frame before trump.  This is pretty high priority since this will appear to a user as a bug.  

Example: 

http://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222016-08-17%22%2C%22end_date%22%3A%222016-8-18%22%2C%22count%22%3A%22videotime%22%2C%22aggregate%22%3A%22day%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22%20WHERE%20onscreen.face1%3DDonald%20Trump%20AND%20onscreen.face2%3DHillary%20Clinton%22%7D%5D%7D

**Comment by jhong93** [comment]
Fixed.
