### ISSUE TITLE
You can still type in the query builder when a field has been filled already

### ISSUE THREAD

**Issue by DanFu09** [jhong93/esper-tv-widget#44]
See here - I have "aws 14th dalai lama" in the query builder already, but I can still type things into the field, which is confusing.
<img width="465" alt="Screen Shot 2019-10-02 at 1 03 14 PM" src="https://user-images.githubusercontent.com/4600866/66077623-29362900-e515-11e9-8230-c06f8b9ca02a.png">

**Comment by jhong93** [comment]
Fixed. This is now allowable behavior.
