### ISSUE TITLE
facen filter options are confusing

### ISSUE THREAD

**Issue by njlxyaoxinwei** [jhong93/esper-tv-widget#53]
It seems that face1 and face2 has no semantic difference. Moreover, (face1=... AND face2=...) does not imply that two distinct faces would satisfy each predicate. Seems to me that they should all be collapsed to just "face" or "one_face".

[using face1](https://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222010-01-01%22%2C%22end_date%22%3A%222018-04-01%22%2C%22count%22%3A%22screen%20time%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20onscreen.face1%3D%5C%22person%3A%20donald%20trump%5C%22%22%7D%5D%7D) and [using face2](https://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222010-01-01%22%2C%22end_date%22%3A%222018-04-01%22%2C%22count%22%3A%22screen%20time%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22COUNT%20%5C%22screen%20time%5C%22%20WHERE%20onscreen.face2%3D%5C%22person%3A%20donald%20trump%5C%22%22%7D%5D%7D)

**Comment by jhong93** [comment]
These have gone away now.
