### ISSUE TITLE
graph drawing error for small date ranges

### ISSUE THREAD

**Issue by kayvonf** [jhong93/esper-tv-widget#6]
Example:

http://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222016-08-17%22%2C%22end_date%22%3A%222016-8-18%22%2C%22count%22%3A%22videotime%22%2C%22aggregate%22%3A%22day%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22%20WHERE%20onscreen.face1%3DDonald%20Trump%20AND%20onscreen.face2%3DHillary%20Clinton%22%7D%5D%7D

<img width="1182" alt="Screen Shot 2019-05-17 at 5 05 02 PM" src="https://user-images.githubusercontent.com/741835/57961774-f96be900-78c5-11e9-866b-09d05917ab89.png">

**Comment by jhong93** [comment]
This is fixed now.
