### ISSUE TITLE
tooltip -- mixes no decimal and decimal numbers

### ISSUE THREAD

**Issue by kayvonf** [jhong93/esper-tv-widget#62]
Different lines have different significant digits, making it hard to compare. (I actually just misread the numbers for this reason.

I recommend making a consistent decision for all lines.  Suggest algorithm: If any line's value is large enough to not render significant digits, then render all lines with 0 sig digits.  If all values are small enough render all lines to one significant digit.

**Comment by jhong93** [comment]
Fixed now
