### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by kayvonf** [jhong93/esper-tv-widget#64]
Somehow this URL triggers it:
https://esper-tv.stanford.edu/?dataVersion=v1&data=%7B%22options%22%3A%7B%22start_date%22%3A%222010-01-01%22%2C%22end_date%22%3A%222019-07-23%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22tag%3D%5C%22male%5C%22%20and%20channel%3D%5C%22cnn%5C%22%20normalize%20tag%3D%5C%22all%5C%22%20and%20channel%3D%5C%22cnn%5C%22%22%7D%2C%7B%22color%22%3A%22%23EDC948%22%2C%22text%22%3A%22tag%3D%5C%22female%5C%22%20and%20channel%3D%5C%22cnn%5C%22%20normalize%20tag%3D%5C%22all%5C%22%20and%20channel%3D%5C%22cnn%5C%22%22%7D%2C%7B%22color%22%3A%22%2359A14F%22%2C%22text%22%3A%22tag%3D%5C%22male%5C%22%20and%20channel%3D%5C%22fox%5C%22%20normalize%20tag%3D%5C%22all%5C%22%20and%20channel%3D%5C%22fox%5C%22%22%7D%2C%7B%22color%22%3A%22%23E15759%22%2C%22text%22%3A%22tag%3D%5C%22female%5C%22%20and%20channel%3D%5C%22fox%5C%22%20normalize%20tag%3D%5C%22all%5C%22%20and%20channel%3D%5C%22fox%5C%22%22%7D%2C%7B%22color%22%3A%22%2376B7B2%22%2C%22text%22%3A%22tag%3D%5C%22male%5C%22%20and%20channel%3D%5C%22msnbc%5C%22%20normalize%20tag%3D%5C%22all%5C%22%20and%20channel%3D%5C%22msnbc%5C%22%22%7D%2C%7B%22color%22%3A%22%23FF9DA7%22%2C%22text%22%3A%22tag%3D%5C%22female%5C%22%20and%20channel%3D%5C%22msnbc%5C%22%20normalize%20tag%3D%5C%22all%5C%22%20and%20channel%3D%5C%22msnbc%5C%22%22%7D%5D%7D

**Comment by jhong93** [comment]
Updated nginx configuration - the issue was request length being too long
